baseURL: http://neni.dev/cv
languageCode: pt-br
title: Felipe Silva | CV
description: Felipe Silva's basic Curriculum Vitae
theme: resume-a4
disableKinds:
  - taxonomy
  - term
  - page
  - section
  - RSS
  - sitemap
  - robotsTXT
  - 404

params:
  useFontAwesome: true
  bib_style: IEEE # IEEE, APA, else

  display:
    experience: true
    education: true
    languages: false
    awards: false
    skills: true
    skills_grouped: false
    interests: true
    contact: true
    linkedin: true
    tagline: true
    aboutMe: true
    projects: false
    publications: false
    certificates: true
    avatar: false

    footer:
      footer: true
      links: true
      credits: true

  title_as:
    experience: Experiências
    education: Formação
    skills: Competências
    certificates: Certificados
    interests: Interesses
    about_me: Sobre mim
    publications: Publications
    projects: Projects

  footer:
    links:
      link:
        - prefix: Powered by
          name: Hugo
          url: https://gohugo.io/

        - prefix: ""
          name: Github Pages
          url: https://pages.github.com/
