baseURL: http://neni.dev/cv
title: Felipe Silva | CV
description: Felipe Silva's basic Curriculum Vitae
languageCode: pt-br

theme: resume-a4
disableKinds: ["taxonomy", "taxonomyTerm", "term", "page", "section", "RSS", "sitemap", "robotsTXT", "404"]

params:
  useFontAwesome: true
  css:
    - print_urls.scss
  header:
    tagline: true
    contact: true
    links: true

  side:
    - feature: education
      title: Formação
    - feature: skills
      title: Competências
      widget: word-list
      style: compact # list, compact, title-list
    - feature: interests
      title: Interesses
      widget: word-list
      style: compact # list, compact, title-list
    - feature: certificates
      title: Certificados

  pages:
    - features:
        - feature: about
          title: Sobre mim
        - feature: experience
          title: Experiências
#    - features:
#        - feature: projects
#          title: Projetos

  footer:
    show: true
    credits: true
